### ISSUE TITLE
2.0 Guidance for install urls that contain multiple destinations?

### ISSUE THREAD

**Issue by subdigital** [Shopify/tophat#60]
I'm updating our internal tool that generates signed S3 URLs for Tophat and the format of the URLs changed. I'm digging through the code to see how multiple destinations are handled after the 2.0 update, but it would be useful to have this in the README.

**Comment by lfroms** [comment]
Hey @subdigital, the example you provided in your second comment is correct and would work.  You may also want to provide platform and destination hints for preheating the device in parallel with the download too, but these are optional:

```
tophat://install?url<signed simulator url>&platform=ios&destination=simulator&url=<signed device url>&platform=ios&destination=simulator
```

We do have an example in the README [here](https://github.com/Shopify/tophat?tab=readme-ov-file#url-format).  See "If multiple artifacts are created for different destinations (...)"
